# Generated by Django 5.2 on 2025-04-16 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(
                        error_messages={"unique": "This email is already registered."},
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                ("phone", models.CharField(max_length=45, unique=True)),
                ("user_role", models.CharField(max_length=45)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="api_user_set",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="api_user_set",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="WasteReport",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("photo", models.ImageField(upload_to="waste_reports/")),
                ("gps_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("gps_lon", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "waste_type",
                    models.CharField(
                        choices=[
                            ("Hazardous", "Hazardous"),
                            ("Recyclable", "Recyclable"),
                            ("General", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("status", models.CharField(default="Reported", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "waste_reports",
            },
        ),
        migrations.CreateModel(
            name="CollectionRoute",
            fields=[
                ("route_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Planned", "Planned"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Delayed", "Delayed"),
                        ],
                        default="Planned",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clerk",
                    models.ForeignKey(
                        limit_choices_to={"user_role__in": ["Clerk", "Manager"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clerk_routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        limit_choices_to={"user_role": "Driver"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reports",
                    models.ManyToManyField(
                        related_name="collection_routes", to="api.wastereport"
                    ),
                ),
            ],
            options={
                "db_table": "collection_routes",
            },
        ),
    ]
